/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get bounded system and component status */
        get: operations["getSystemStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stable workflow state names */
        get: operations["listWorkflowStates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a bounded page of jobs */
        get: operations["listJobs"];
        put?: never;
        /** Submit a maintenance job */
        post: operations["createJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        /** Inspect one job and its durable timeline */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobID}/events": {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        /** Stream replayable job transition events */
        get: operations["streamJobEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobID}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        /** List immutable evidence artifacts for one job */
        get: operations["listJobArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobID}/artifacts/{artifactID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
                artifactID: components["parameters"]["ArtifactID"];
            };
            cookie?: never;
        };
        /** Download one integrity-checked job evidence artifact */
        get: operations["downloadJobArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobID}/actions/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel an active or waiting job */
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobID}/actions/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Requeue a failed or cancelled job */
        post: operations["retryJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current validated configuration */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a proposed configuration without saving it */
        post: operations["validateConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configuration revision history */
        get: operations["listConfigRevisions"];
        put?: never;
        /** Validate and save a configuration revision */
        post: operations["createConfigRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/revisions/{revisionID}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionID: components["parameters"]["RevisionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new revision matching a selected rollback point */
        post: operations["rollbackConfigRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List append-only audit events */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        JobState: "queued" | "syncing" | "preparing_dependencies" | "creating_worktree" | "locking_acceptance_criteria" | "loading_implementation_model" | "reproducing" | "implementing" | "verifying_targeted" | "verifying_full" | "loading_qc_model" | "qc_review" | "awaiting_repair" | "repairing" | "final_verification" | "awaiting_operator" | "publishing_branch" | "draft_pr_created" | "completed" | "failed" | "cancelled";
        CreateJobRequest: {
            project_id: string;
            repository: string;
            task: string;
            issue_number?: number;
        };
        Job: {
            id: string;
            project_id: string;
            repository: string;
            task: string;
            issue_number?: number;
            state: components["schemas"]["JobState"];
            base_sha?: string;
            result_sha?: string;
            acceptance_criteria: Record<string, never>[];
            acceptance_criteria_hash?: string;
            review_cycle: number;
            version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Transition: {
            sequence: number;
            job_id: string;
            from?: components["schemas"]["JobState"];
            to: components["schemas"]["JobState"];
            actor_id: string;
            reason: string;
            details: Record<string, never>;
            /** Format: date-time */
            created_at: string;
        };
        Artifact: {
            id: string;
            job_id: string;
            project_id: string;
            sha256: string;
            bytes: number;
            kind: string;
            media_type: string;
            producer: string;
            metadata: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        SystemStatus: {
            status: string;
            profile: string;
            uptime_seconds: number;
            components: {
                [key: string]: string;
            };
        };
        SystemConfig: {
            /** @constant */
            schema_version: 1;
            deployment: {
                listen_address: string;
                data_root: string;
                /** @enum {string} */
                profile: "mock" | "production";
            };
            workflow: {
                max_review_cycles: number;
                max_wall_seconds: number;
                max_log_bytes: number;
            };
            qc: {
                block_on: ("blocker" | "must_fix" | "should_fix" | "note")[];
                require_evidence_for_blocking: boolean;
                require_verification_method: boolean;
                human_waiver_enabled: boolean;
                waiver_rationale_required: boolean;
            };
            protected_paths: {
                patterns: string[];
            };
        };
        ConfigDocumentRequest: {
            document: components["schemas"]["SystemConfig"];
            reason?: string;
        };
        ValidationResult: {
            valid: boolean;
            errors: string[];
        };
        ConfigRevision: {
            id: string;
            sequence: number;
            actor_id: string;
            /** @constant */
            schema_version: 1;
            before: {
                [key: string]: unknown;
            };
            after: components["schemas"]["SystemConfig"];
            diff: {
                [key: string]: unknown;
            }[];
            validation_result: components["schemas"]["ValidationResult"];
            rollback_of?: string;
            reason: string;
            /** Format: date-time */
            created_at: string;
        };
    };
    responses: {
        /** @description Structured error */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: {
                        code: string;
                        message: string;
                    };
                };
            };
        };
    };
    parameters: {
        JobID: string;
        RevisionID: string;
        ArtifactID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSystemStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current bounded component status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    listWorkflowStates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stable workflow state names */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["JobState"][];
                    };
                };
            };
            400: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    listJobs: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded job page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Job"][];
                        limit: number;
                        offset: number;
                    };
                };
            };
            400: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    createJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Durable queued job */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["ErrorResponse"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job plus durable state timeline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        job: components["schemas"]["Job"];
                        transitions: components["schemas"]["Transition"][];
                    };
                };
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
    streamJobEvents: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded replayable server-sent transition events; Last-Event-ID is supported. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    listJobArtifacts: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job-scoped artifact metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Artifact"][];
                    };
                };
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
    downloadJobArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
                artifactID: components["parameters"]["ArtifactID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verified artifact bytes; Content-Type reflects stored media metadata. */
            200: {
                headers: {
                    "X-Artifact-SHA256"?: string;
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            404: components["responses"]["ErrorResponse"];
            503: components["responses"]["ErrorResponse"];
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            409: components["responses"]["ErrorResponse"];
            422: components["responses"]["ErrorResponse"];
        };
    };
    retryJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requeued failed or cancelled job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            409: components["responses"]["ErrorResponse"];
            422: components["responses"]["ErrorResponse"];
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current validated configuration and revision metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        revision: components["schemas"]["ConfigRevision"];
                        document: components["schemas"]["SystemConfig"];
                    };
                };
            };
            400: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    validateConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigDocumentRequest"];
            };
        };
        responses: {
            /** @description Validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            400: components["responses"]["ErrorResponse"];
        };
    };
    listConfigRevisions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest-first configuration revisions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ConfigRevision"][];
                    };
                };
            };
            400: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    createConfigRevision: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigDocumentRequest"];
            };
        };
        responses: {
            /** @description Created configuration revision */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigRevision"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
            422: components["responses"]["ErrorResponse"];
        };
    };
    rollbackConfigRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionID: components["parameters"]["RevisionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Created rollback revision */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigRevision"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
            422: components["responses"]["ErrorResponse"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded append-only audit page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            400: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
}
