/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report whether one-time administrator bootstrap is complete */
        get: operations["getAuthenticationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create the one-time local administrator and authenticated session */
        post: operations["bootstrapAdministrator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a bounded local session */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current principal and rotate its CSRF token */
        get: operations["getAuthenticationSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reauthenticate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reauthenticate the current session for a five-minute sensitive-action window */
        post: operations["reauthenticate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get bounded system and component status */
        get: operations["getSystemStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stable workflow state names */
        get: operations["listWorkflowStates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered repository projects */
        get: operations["listProjects"];
        put?: never;
        /** Register or update a validated project */
        post: operations["upsertProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/memory": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        /** Browse or perform a bounded project-scoped canonical memory retrieval */
        get: operations["listProjectMemory"];
        put?: never;
        /** Create a secret-scanned provisional memory candidate in the registered project scope */
        post: operations["createProjectMemory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/memory/retrievals": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        /** List append-only retrieval traces for one registered project */
        get: operations["listProjectMemoryRetrievals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/memory/{memoryID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
                memoryID: components["parameters"]["MemoryID"];
            };
            cookie?: never;
        };
        /** Inspect one memory record only within its registered project scope */
        get: operations["getProjectMemory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/memory/{memoryID}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
                memoryID: components["parameters"]["MemoryID"];
            };
            cookie?: never;
        };
        /** List the append-only lifecycle for one project memory record */
        get: operations["listProjectMemoryEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/memory/{memoryID}/actions/promote": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
                memoryID: components["parameters"]["MemoryID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote an eligible quarantined record after reviewer or administrator approval */
        post: operations["promoteProjectMemory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/memory/{memoryID}/actions/correct": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
                memoryID: components["parameters"]["MemoryID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Correct a memory record and return it to quarantine */
        post: operations["correctProjectMemory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/memory/{memoryID}/actions/invalidate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
                memoryID: components["parameters"]["MemoryID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a quarantined or canonical memory record stale */
        post: operations["invalidateProjectMemory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/memory/{memoryID}/actions/delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
                memoryID: components["parameters"]["MemoryID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear memory content after administrator recent reauthentication */
        post: operations["deleteProjectMemory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a bounded page of jobs */
        get: operations["listJobs"];
        put?: never;
        /** Submit a maintenance job */
        post: operations["createJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        /** Inspect one job and its durable timeline */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobID}/events": {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        /** Stream replayable job transition events */
        get: operations["streamJobEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobID}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        /** List immutable evidence artifacts for one job */
        get: operations["listJobArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobID}/artifacts/{artifactID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
                artifactID: components["parameters"]["ArtifactID"];
            };
            cookie?: never;
        };
        /** Download one integrity-checked job evidence artifact */
        get: operations["downloadJobArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobID}/actions/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel an active or waiting job */
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobID}/actions/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Requeue a failed or cancelled job */
        post: operations["retryJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobID}/actions/approve-publication": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve exact-result draft publication after recent reauthentication */
        post: operations["approvePublication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current validated configuration */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a proposed configuration without saving it */
        post: operations["validateConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configuration revision history */
        get: operations["listConfigRevisions"];
        put?: never;
        /** Validate and save a configuration revision */
        post: operations["createConfigRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/revisions/{revisionID}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionID: components["parameters"]["RevisionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new revision matching a selected rollback point */
        post: operations["rollbackConfigRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List append-only audit events */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id: string;
            username: string;
            display_name: string;
            /** @enum {string} */
            role: "viewer" | "operator" | "reviewer" | "administrator";
            disabled: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Principal: {
            user: components["schemas"]["User"];
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            reauthenticated_until?: string;
        };
        AuthenticationResult: {
            principal: components["schemas"]["Principal"];
            csrf_token: string;
        };
        BootstrapRequest: {
            username: string;
            display_name: string;
            password: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        UpsertProjectRequest: {
            id: string;
            /** @enum {string} */
            provider: "local" | "github";
            repository: string;
            default_branch: string;
            local_remote_name?: string;
        };
        Project: components["schemas"]["UpsertProjectRequest"] & {
            enabled: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @enum {string} */
        MemoryStatus: "quarantine" | "canonical" | "stale" | "deleted";
        MemoryScope: {
            owner: string;
            repository: string;
        };
        MemoryCandidateRequest: {
            content: string;
            /** @enum {string} */
            kind?: "project_knowledge" | "verified_case" | "failed_case" | "pattern" | "known_issue" | "flaky_test" | "issue_history";
            source_uri?: string;
            base_commit?: string;
            merged_commit?: string;
            affected_paths?: string[];
            invalidation_rule?: string;
            /** Format: date-time */
            expires_at?: string;
        };
        MemoryPromotionRequest: {
            rationale: string;
            /** @enum {string} */
            basis: "deterministic_verification" | "merged_pr" | "human_approval";
            merged_commit?: string;
            expected_version: number;
        };
        MemoryCorrectionRequest: {
            content: string;
            affected_paths?: string[];
            invalidation_rule?: string;
            rationale: string;
            expected_version: number;
        };
        MemoryLifecycleRequest: {
            rationale: string;
            expected_version: number;
        };
        MemoryRecord: {
            id: string;
            scope: components["schemas"]["MemoryScope"];
            namespace: string;
            content: string;
            content_hash: string;
            source_uri: string;
            base_commit: string;
            merged_commit?: string;
            affected_paths: string[];
            status: components["schemas"]["MemoryStatus"];
            verified: boolean;
            secret_scan_pass: boolean;
            kind: string;
            invalidation_rule?: string;
            /** Format: date-time */
            expires_at?: string;
            /** Format: date-time */
            deleted_at?: string;
            version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        MemoryEvent: {
            sequence: number;
            record_id: string;
            scope: components["schemas"]["MemoryScope"];
            action: string;
            actor_id: string;
            rationale: string;
            details: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        MemoryRetrievalTrace: {
            id: string;
            job_id?: string;
            scope: components["schemas"]["MemoryScope"];
            namespace: string;
            query: string;
            query_hash: string;
            candidate_ids: string[];
            selected_ids: string[];
            budget_tokens: number;
            allocated_tokens: number;
            trajectory: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        /** @enum {string} */
        JobState: "queued" | "syncing" | "preparing_dependencies" | "creating_worktree" | "locking_acceptance_criteria" | "loading_implementation_model" | "reproducing" | "implementing" | "verifying_targeted" | "verifying_full" | "loading_qc_model" | "qc_review" | "awaiting_repair" | "repairing" | "final_verification" | "awaiting_operator" | "publishing_branch" | "draft_pr_created" | "completed" | "failed" | "cancelled";
        CreateJobRequest: {
            project_id: string;
            repository: string;
            task: string;
            issue_number?: number;
        };
        Job: {
            id: string;
            project_id: string;
            repository: string;
            task: string;
            issue_number?: number;
            state: components["schemas"]["JobState"];
            base_sha?: string;
            result_sha?: string;
            acceptance_criteria: Record<string, never>[];
            acceptance_criteria_hash?: string;
            review_cycle: number;
            version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Transition: {
            sequence: number;
            job_id: string;
            from?: components["schemas"]["JobState"];
            to: components["schemas"]["JobState"];
            actor_id: string;
            reason: string;
            details: Record<string, never>;
            /** Format: date-time */
            created_at: string;
        };
        Artifact: {
            id: string;
            job_id: string;
            project_id: string;
            sha256: string;
            bytes: number;
            kind: string;
            media_type: string;
            producer: string;
            metadata: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        Finding: {
            job_id: string;
            id: string;
            /** @enum {string} */
            severity: "blocker" | "must_fix" | "should_fix" | "note";
            category: string;
            claim: string;
            location: {
                [key: string]: unknown;
            };
            required_resolution: string;
            verification_method: string;
            /** @enum {string} */
            status: "open" | "fixed" | "verified" | "disputed" | "accepted" | "rejected" | "human_waived" | "closed";
            first_seen_cycle: number;
            last_seen_cycle: number;
            version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Approval: {
            id: string;
            job_id: string;
            kind: string;
            subject_sha: string;
            actor_id: string;
            /** @enum {string} */
            actor_role: "reviewer" | "administrator";
            rationale: string;
            reauthenticated: boolean;
            /** Format: date-time */
            created_at: string;
        };
        PhaseRecord: {
            job_id: string;
            phase_state: components["schemas"]["JobState"];
            phase_version: number;
            outcome: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        SystemStatus: {
            status: string;
            profile: string;
            uptime_seconds: number;
            components: {
                [key: string]: string;
            };
        };
        SystemConfig: {
            /** @constant */
            schema_version: 1;
            deployment: {
                listen_address: string;
                data_root: string;
                /** @enum {string} */
                profile: "mock" | "production";
            };
            workflow: {
                max_review_cycles: number;
                max_wall_seconds: number;
                max_log_bytes: number;
            };
            qc: {
                block_on: ("blocker" | "must_fix" | "should_fix" | "note")[];
                require_evidence_for_blocking: boolean;
                require_verification_method: boolean;
                human_waiver_enabled: boolean;
                waiver_rationale_required: boolean;
            };
            protected_paths: {
                patterns: string[];
            };
        };
        ConfigDocumentRequest: {
            document: components["schemas"]["SystemConfig"];
            reason?: string;
        };
        ValidationResult: {
            valid: boolean;
            errors: string[];
        };
        ConfigRevision: {
            id: string;
            sequence: number;
            actor_id: string;
            /** @constant */
            schema_version: 1;
            before: {
                [key: string]: unknown;
            };
            after: components["schemas"]["SystemConfig"];
            diff: {
                [key: string]: unknown;
            }[];
            validation_result: components["schemas"]["ValidationResult"];
            rollback_of?: string;
            reason: string;
            /** Format: date-time */
            created_at: string;
        };
    };
    responses: {
        /** @description Structured error */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: {
                        code: string;
                        message: string;
                    };
                };
            };
        };
    };
    parameters: {
        JobID: string;
        RevisionID: string;
        ArtifactID: string;
        ProjectID: string;
        MemoryID: string;
        CSRFToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAuthenticationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authentication bootstrap status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        bootstrapped: boolean;
                        authentication_enabled: boolean;
                    };
                };
            };
            400: components["responses"]["ErrorResponse"];
        };
    };
    bootstrapAdministrator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BootstrapRequest"];
            };
        };
        responses: {
            /** @description Bootstrap administrator session */
            201: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationResult"];
                };
            };
            409: components["responses"]["ErrorResponse"];
            422: components["responses"]["ErrorResponse"];
            429: components["responses"]["ErrorResponse"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated session */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationResult"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            429: components["responses"]["ErrorResponse"];
        };
    };
    getAuthenticationSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current principal and fresh CSRF token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationResult"];
                };
            };
            401: components["responses"]["ErrorResponse"];
        };
    };
    reauthenticate: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        responses: {
            /** @description Recently reauthenticated principal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        principal: components["schemas"]["Principal"];
                    };
                };
            };
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            429: components["responses"]["ErrorResponse"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked and cookie expired */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    getSystemStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current bounded component status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    listWorkflowStates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stable workflow state names */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["JobState"][];
                    };
                };
            };
            400: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Project"][];
                    };
                };
            };
            400: components["responses"]["ErrorResponse"];
        };
    };
    upsertProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertProjectRequest"];
            };
        };
        responses: {
            /** @description Registered project */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
            422: components["responses"]["ErrorResponse"];
        };
    };
    listProjectMemory: {
        parameters: {
            query?: {
                q?: string;
                status?: components["schemas"]["MemoryStatus"];
                limit?: number;
            };
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project memory records and, for search, its bounded retrieval trace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["MemoryRecord"][];
                        namespace: string;
                        retrieval?: components["schemas"]["MemoryRetrievalTrace"];
                    };
                };
            };
            404: components["responses"]["ErrorResponse"];
            422: components["responses"]["ErrorResponse"];
        };
    };
    createProjectMemory: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryCandidateRequest"];
            };
        };
        responses: {
            /** @description Quarantined memory candidate */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryRecord"];
                };
            };
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            422: components["responses"]["ErrorResponse"];
        };
    };
    listProjectMemoryRetrievals: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project retrieval history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["MemoryRetrievalTrace"][];
                    };
                };
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
    getProjectMemory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
                memoryID: components["parameters"]["MemoryID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project memory record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryRecord"];
                };
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
    listProjectMemoryEvents: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
                memoryID: components["parameters"]["MemoryID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memory record events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["MemoryEvent"][];
                    };
                };
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
    promoteProjectMemory: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                projectID: components["parameters"]["ProjectID"];
                memoryID: components["parameters"]["MemoryID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryPromotionRequest"];
            };
        };
        responses: {
            /** @description Canonical memory record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryRecord"];
                };
            };
            403: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
            422: components["responses"]["ErrorResponse"];
        };
    };
    correctProjectMemory: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                projectID: components["parameters"]["ProjectID"];
                memoryID: components["parameters"]["MemoryID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryCorrectionRequest"];
            };
        };
        responses: {
            /** @description Corrected quarantined memory record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryRecord"];
                };
            };
            403: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
            422: components["responses"]["ErrorResponse"];
        };
    };
    invalidateProjectMemory: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                projectID: components["parameters"]["ProjectID"];
                memoryID: components["parameters"]["MemoryID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryLifecycleRequest"];
            };
        };
        responses: {
            /** @description Stale memory record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryRecord"];
                };
            };
            403: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
            422: components["responses"]["ErrorResponse"];
        };
    };
    deleteProjectMemory: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                projectID: components["parameters"]["ProjectID"];
                memoryID: components["parameters"]["MemoryID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryLifecycleRequest"];
            };
        };
        responses: {
            /** @description Memory content cleared and tombstone retained */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
            422: components["responses"]["ErrorResponse"];
        };
    };
    listJobs: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded job page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Job"][];
                        limit: number;
                        offset: number;
                    };
                };
            };
            400: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    createJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Durable queued job */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["ErrorResponse"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job plus durable state timeline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        job: components["schemas"]["Job"];
                        transitions: components["schemas"]["Transition"][];
                        findings: components["schemas"]["Finding"][];
                        approvals: components["schemas"]["Approval"][];
                        phases: components["schemas"]["PhaseRecord"][];
                    };
                };
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
    streamJobEvents: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded replayable server-sent transition events; Last-Event-ID is supported. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    listJobArtifacts: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job-scoped artifact metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Artifact"][];
                    };
                };
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
    downloadJobArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
                artifactID: components["parameters"]["ArtifactID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verified artifact bytes; Content-Type reflects stored media metadata. */
            200: {
                headers: {
                    "X-Artifact-SHA256"?: string;
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            404: components["responses"]["ErrorResponse"];
            503: components["responses"]["ErrorResponse"];
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            409: components["responses"]["ErrorResponse"];
            422: components["responses"]["ErrorResponse"];
        };
    };
    retryJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requeued failed or cancelled job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            409: components["responses"]["ErrorResponse"];
            422: components["responses"]["ErrorResponse"];
        };
    };
    approvePublication: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    rationale: string;
                };
            };
        };
        responses: {
            /** @description Exact-SHA approval and publishing job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        job: components["schemas"]["Job"];
                        approval: components["schemas"]["Approval"];
                    };
                };
            };
            400: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
            422: components["responses"]["ErrorResponse"];
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current validated configuration and revision metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        revision: components["schemas"]["ConfigRevision"];
                        document: components["schemas"]["SystemConfig"];
                    };
                };
            };
            400: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    validateConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigDocumentRequest"];
            };
        };
        responses: {
            /** @description Validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            400: components["responses"]["ErrorResponse"];
        };
    };
    listConfigRevisions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest-first configuration revisions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ConfigRevision"][];
                    };
                };
            };
            400: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    createConfigRevision: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigDocumentRequest"];
            };
        };
        responses: {
            /** @description Created configuration revision */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigRevision"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
            422: components["responses"]["ErrorResponse"];
        };
    };
    rollbackConfigRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionID: components["parameters"]["RevisionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Created rollback revision */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigRevision"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
            422: components["responses"]["ErrorResponse"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded append-only audit page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            400: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
}
