import axe from "axe-core";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { CapabilityPage } from "./CapabilityPage";
import { setCSRFToken } from "./api/client";

const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}});
const project={id:"project-one",provider:"local",repository:"owner/repo",default_branch:"main",local_remote_name:"fixture.git",enabled:true,created_at:"2026-07-20T22:00:00Z",updated_at:"2026-07-20T22:00:00Z"};
const manifest={schema_version:1,id:"php83-intranet",name:"PHP 8.3 intranet",version:"1.0.0",checksum_sha256:"a".repeat(64),description:"Evidence-driven PHP verification.",languages:["php"],compatibility:{controller_constraint:">=2.0.0",platforms:["linux/amd64"]},prerequisites:[],detection_rules:[],runner_profile_ids:["php83-verify"],operation_classes:["composer-validate"],parser_ids:["junit-v1"],policy_fragments:[],context_selectors:[],risk_rules:[],documentation_rules:[],workflow_changes:[{stage:"verify",operation_id:"composer-validate",required:true,description:"Validate metadata."}],ui_schema:[],rehearsals:[{id:"php-web-journey",kind:"browser",operation_id:"playwright-test",artifact_kinds:["screenshot"],comparison_class:"masked-visual",approval_policy:"review-required"}]};
const evidence={path:"composer.json",observation:"trusted snapshot path and content hash",sha256:"b".repeat(64)};
const proposal={id:"proposal_11111111111111111111111111111111",scan_id:"scan_11111111111111111111111111111111",project_id:"project-one",kind:"capability_pack",key:"php83-intranet",value:{pack_id:"php83-intranet",version:"1.0.0",enabled:false},confidence:95,evidence:[evidence],state:"pending",version:1};
const scan={id:"scan_11111111111111111111111111111111",project_id:"project-one",repository:"owner/repo",revision:"abc123",state:"complete",findings:[{category:"framework",value:"composer",confidence:95,evidence:[evidence]}],proposals:[proposal],drift:[],files_observed:3,excluded_files:0,created_at:"2026-07-20T22:00:00Z"};

describe("CapabilityPage",()=>{const requests:Request[]=[];beforeEach(()=>{setCSRFToken("csrf-token-with-at-least-thirty-two-characters");vi.stubGlobal("confirm",vi.fn(()=>true));vi.stubGlobal("fetch",vi.fn(async(input:RequestInfo|URL)=>{const request=input instanceof Request?input:new Request(input);requests.push(request.clone());const path=new URL(request.url).pathname;
  if(path==="/api/v1/projects")return response({items:[project]});if(path==="/api/v1/capability-packs")return response({schema_version:1,items:[manifest]});if(path==="/api/v1/capability-packs/installations")return response({items:[]});if(path.endsWith("/capability-packs"))return response({items:[]});if(path.endsWith("/repo-doctor/scans"))return response({items:[scan]});if(path.endsWith("/repo-doctor/actions/scan"))return response(scan,201);if(path.endsWith("/actions/preview"))return response({action:"install",workflow_changes:manifest.workflow_changes,trust:{checksum_valid:true,authority_safe:true,compatible:true}});if(path.endsWith("/actions/dry-run"))return response({proposal,will_modify_repository:false,requires_explicit_acceptance:true,valid:true});return response({error:{code:"unmocked",message:`${request.method} ${path}`}},404)}))});afterEach(()=>{cleanup();requests.length=0;vi.unstubAllGlobals()});
  it("keeps scan source trusted and previews evidence-backed proposals accessibly",async()=>{const {container}=render(<CapabilityPage/>);expect(await screen.findByText("Evidence-driven PHP verification.")).toBeInTheDocument();expect((await screen.findAllByText(/composer.json/)).length).toBeGreaterThan(0);fireEvent.click(screen.getByRole("button",{name:"Run Repo Doctor"}));expect(await screen.findByText(/completed without repository changes/)).toBeInTheDocument();const scanRequest=requests.find((item)=>new URL(item.url).pathname.endsWith("/repo-doctor/actions/scan"));expect(scanRequest?.method).toBe("POST");expect(await scanRequest?.clone().text()).toBe("");fireEvent.change(screen.getByLabelText("Audited reason"),{target:{value:"reviewed repository evidence"}});fireEvent.click(screen.getByRole("button",{name:"Dry run proposal"}));expect(await screen.findByText(/Proposal dry run completed/)).toBeInTheDocument();const dryRun=requests.find((item)=>new URL(item.url).pathname.endsWith("/actions/dry-run"));expect(dryRun?.headers.get("X-CSRF-Token")).toBe("csrf-token-with-at-least-thirty-two-characters");await waitFor(async()=>expect((await axe.run(container,{runOnly:{type:"tag",values:["wcag2a","wcag2aa"]}})).violations).toEqual([]))});
});
