import { FormEvent, useCallback, useEffect, useState } from "react";
import { BrainCircuit, Database, FileSearch, RefreshCw, Search, ShieldCheck, Trash2 } from "lucide-react";
import { api, getCSRFToken } from "./api/client";
import type { components } from "./api/schema";

type Project = components["schemas"]["Project"];
type Status = components["schemas"]["IntelligenceStatus"];
type QueryResult = components["schemas"]["IntelligenceQueryResult"];
type ContextManifest = components["schemas"]["ContextManifest"];
type Baseline = components["schemas"]["VerificationBaseline"];
type Differential = components["schemas"]["VerificationDifferential"];
type TestImpact = components["schemas"]["TestImpact"];
type CacheEntry = components["schemas"]["CacheEntry"];

function short(value?: string): string { return value ? `${value.slice(0, 12)}…` : "—"; }
function date(value?: string): string { return value ? new Date(value).toLocaleString() : "—"; }
function errorMessage(error: unknown, fallback: string): string { if (error && typeof error === "object" && "error" in error) { const nested=(error as {error?:{message?:string}}).error;if(nested?.message)return nested.message; } return fallback; }

export function IntelligencePage() {
  const [projects,setProjects]=useState<Project[]>([]);const [projectID,setProjectID]=useState("");
  const [status,setStatus]=useState<Status|null>(null);const [manifests,setManifests]=useState<ContextManifest[]>([]);const [baselines,setBaselines]=useState<Baseline[]>([]);const [differentials,setDifferentials]=useState<Differential[]>([]);const [impacts,setImpacts]=useState<TestImpact[]>([]);const [caches,setCaches]=useState<CacheEntry[]>([]);
  const [query,setQuery]=useState("");const [queryResult,setQueryResult]=useState<QueryResult|null>(null);const [reason,setReason]=useState("");const [password,setPassword]=useState("");const [message,setMessage]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);setError("");const projectResult=await api.GET("/projects");const items=projectResult.data?.items??[];setProjects(items);const selected=projectID||items[0]?.id||"";if(!projectID&&selected)setProjectID(selected);if(!selected){setLoading(false);return}const path={projectID:selected};const [statusResult,manifestResult,baselineResult,differentialResult,impactResult,cacheResult]=await Promise.all([
    api.GET("/projects/{projectID}/intelligence/status",{params:{path}}),api.GET("/projects/{projectID}/context-manifests",{params:{path}}),api.GET("/projects/{projectID}/baselines",{params:{path}}),api.GET("/projects/{projectID}/differentials",{params:{path}}),api.GET("/projects/{projectID}/test-impacts",{params:{path}}),api.GET("/projects/{projectID}/caches",{params:{path}}),
  ]);if(!statusResult.data)setError(errorMessage(statusResult.error,"Intelligence status could not be loaded."));setStatus(statusResult.data??null);setManifests(manifestResult.data?.items??[]);setBaselines(baselineResult.data?.items??[]);setDifferentials(differentialResult.data?.items??[]);setImpacts(impactResult.data?.items??[]);setCaches(cacheResult.data?.items??[]);setLoading(false)},[projectID]);
  useEffect(()=>{void load()},[load]);
  const refresh=async()=>{if(!projectID)return;setError("");const result=await api.POST("/projects/{projectID}/intelligence/actions/refresh",{params:{path:{projectID},header:{"X-CSRF-Token":getCSRFToken()}}});if(!result.data){setError(errorMessage(result.error,"Trusted repository refresh failed."));return}setMessage(`Indexed ${result.data.run.files} file(s): ${result.data.run.parsed} parsed, ${result.data.run.reused} reused, ${result.data.run.failures} partial failure(s); ${result.data.source_excluded} oversized or unsupported source item(s) excluded.`);await load()};
  const search=async(event:FormEvent)=>{event.preventDefault();if(!projectID||!query.trim())return;const result=await api.POST("/projects/{projectID}/intelligence/query",{params:{path:{projectID},header:{"X-CSRF-Token":getCSRFToken()}},body:{term:query,limit:100}});if(!result.data){setError(errorMessage(result.error,"Query failed."));return}setQueryResult(result.data)};
  const reauthenticate=async()=>{if(!password){setError("Enter the administrator password for destructive derived-data actions.");return false}const result=await api.POST("/auth/reauthenticate",{params:{header:{"X-CSRF-Token":getCSRFToken()}},body:{password}});setPassword("");if(!result.data){setError("Reauthentication failed.");return false}return true};
  const rebuild=async()=>{if(!projectID||!reason.trim()||!await reauthenticate())return;if(!window.confirm("Clear this project's derived index? Durable source and job evidence are not deleted."))return;const result=await api.POST("/projects/{projectID}/intelligence/actions/rebuild",{params:{path:{projectID},header:{"X-CSRF-Token":getCSRFToken()}},body:{reason}});if(!result.data){setError(errorMessage(result.error,"Rebuild clear failed."));return}setMessage("Derived index cleared. Run Refresh index to build it from the exact synchronized Git revision.");await load()};
  const purgeCaches=async(kind:string)=>{if(!projectID||!reason.trim()||!await reauthenticate())return;const matching=caches.filter((entry)=>!kind||entry.kind===kind).length;if(!window.confirm(`Purge ${matching} displayed ${kind||"all"} cache entr${matching===1?"y":"ies"} for ${projectID}?`))return;const result=await api.POST("/projects/{projectID}/caches/actions/purge",{params:{path:{projectID},header:{"X-CSRF-Token":getCSRFToken()}},body:{kind,reason}});if(!result.data){setError(errorMessage(result.error,"Cache purge failed."));return}setMessage(`Purged ${result.data.purged} exact cache entr${result.data.purged===1?"y":"ies"}.`);await load()};
  return <>
    <p className="page-intro">Inspect project-separated blob-hash analysis, deterministic context selection, clean-environment differentials, explainable test impact, and verified cache provenance.</p>
    <section className="configuration-toolbar" aria-label="Code intelligence project controls"><label>Registered project<select value={projectID} onChange={(event)=>setProjectID(event.target.value)}><option value="">Select a project</option>{projects.map((project)=><option key={project.id} value={project.id}>{project.id} · {project.repository}</option>)}</select></label><button type="button" disabled={!projectID||loading} onClick={()=>void refresh()}><RefreshCw aria-hidden="true"/>Refresh index</button><button className="secondary-button" type="button" disabled={!projectID||loading} onClick={()=>void load()}><RefreshCw aria-hidden="true"/>Reload evidence</button></section>
    {error&&<p className="error" role="alert">{error}</p>}{message&&<p className="inline-message" role="status">{message}</p>}
    <div className="configuration-summary"><div><span>Index state</span><strong>{status?.state??"—"}</strong></div><div><span>Files</span><strong>{status?.files??0}</strong></div><div><span>Partial failures</span><strong>{status?.failures??0}</strong></div><div><span>Derived bytes</span><strong>{(status?.storage_bytes??0).toLocaleString()}</strong></div></div>
    <section className="content-section"><div className="section-heading"><div><p className="eyebrow">Freshness and coverage</p><h2>Project index</h2></div><BrainCircuit aria-hidden="true"/></div>{!status||status.state==="never_indexed"?<div className="empty-state"><FileSearch aria-hidden="true"/><div><strong>No index run yet</strong><p>Refresh reads a bounded exact snapshot from the credential-isolated Git bridge; source bytes are never accepted from this browser.</p></div></div>:<div className="detail-grid"><article><h3>Revision</h3><code>{status.latest_revision}</code><p>{date(status.fresh_at)}</p></article><article><h3>Languages</h3><p>{status.languages.join(", ")||"None classified"}</p><small>{status.parser_ids.join(", ")}</small></article><article><h3>Run identity</h3><code>{status.latest_run_id}</code><p>Blob results are reused only within this project/repository/parser identity.</p></article></div>}
      <form className="intelligence-query" onSubmit={(event)=>void search(event)}><label>Graph query<input type="search" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Symbol, import, or repository path"/></label><button type="submit" disabled={!projectID||!query.trim()}><Search aria-hidden="true"/>Query evidence</button></form>
      {queryResult&&<div className="query-results"><p>{queryResult.partial?"Partial index: failures remain visible.":"Complete indexed evidence."} {queryResult.symbols.length} symbol(s), {queryResult.relations.length} relation(s).</p><div className="table-scroll" tabIndex={0}><table><thead><tr><th>Symbol</th><th>Kind</th><th>Location</th><th>Confidence</th></tr></thead><tbody>{queryResult.symbols.map((symbol)=><tr key={symbol.id}><td>{symbol.name}</td><td>{symbol.kind}</td><td><code>{symbol.path}:{symbol.start_line}</code></td><td>{symbol.confidence}%</td></tr>)}</tbody></table></div></div>}
    </section>
    <section className="content-section"><div className="section-heading"><div><p className="eyebrow">Bounded deterministic packets</p><h2>Context manifests</h2></div><ShieldCheck aria-hidden="true"/></div>{manifests.length===0?<div className="empty-state"><Database aria-hidden="true"/><div><strong>No compiled contexts yet</strong><p>Workflow stages record selection reasons, hashes, trust, cost, exclusions, staleness, and reserved output budget—never hidden reasoning.</p></div></div>:<div className="evidence-stack">{manifests.map((manifest)=><details key={manifest.id}><summary><code>{manifest.id}</code> · {manifest.stage} · {manifest.used_tokens}/{manifest.budget_tokens-manifest.reserved_output_tokens} input tokens</summary><p>{manifest.truncated?"Budget truncation occurred.":"All eligible content fit."} Created {date(manifest.created_at)}.</p><ul>{manifest.selections.map((selection)=><li key={selection.id}><strong>{selection.included?"Included":"Excluded"}</strong> {selection.source} / {selection.id}: {selection.reason} · {selection.estimated_tokens} tokens · {selection.trust}{selection.exclusion?` · ${selection.exclusion}`:""}</li>)}</ul></details>)}</div>}</section>
    <section className="content-section"><div className="section-heading"><div><p className="eyebrow">Fresh clean-environment evidence</p><h2>Baselines and differentials</h2></div><span>{baselines.length} baseline(s)</span></div>{baselines.length===0?<div className="empty-state"><ShieldCheck aria-hidden="true"/><div><strong>No workflow baseline captured</strong><p>Agents cannot create or approve baseline state. A policy-bound clean verification phase records the first immutable baseline.</p></div></div>:<div className="evidence-stack">{baselines.map((baseline)=><article key={baseline.id}><strong>{baseline.reason}</strong><p><code>{short(baseline.revision)}</code> · {baseline.toolchain_id} · {baseline.observations.length} observation(s) · {date(baseline.created_at)}</p></article>)}</div>}{differentials.map((differential)=><details key={differential.id}><summary>{short(differential.candidate_sha)} against {differential.baseline_id}</summary><ul>{differential.items.map((item)=><li key={`${item.kind}-${item.key}`}><strong>{item.classification.replaceAll("_"," ")}</strong> {item.kind}/{item.key}: {item.explanation}</li>)}</ul></details>)}</section>
    <section className="content-section"><div className="section-heading"><div><p className="eyebrow">Fast inner loop, full final gate</p><h2>Test impact</h2></div><span>{impacts.length} record(s)</span></div>{impacts.length===0?<div className="empty-state"><FileSearch aria-hidden="true"/><div><strong>No changed-symbol impact yet</strong><p>Selections will cite coverage/index relationships and omissions. Targeted tests never replace the policy-required fresh full suite.</p></div></div>:impacts.map((impact)=><details key={impact.id}><summary>{short(impact.revision)} · {impact.selections.filter((item)=>item.selected).length} targeted · full suite {impact.full_suite_required?"required":"policy dependent"}</summary><p>{impact.policy_explanation}</p><ul>{impact.selections.map((selection)=><li key={selection.test_id}><strong>{selection.selected?"Selected":"Omitted"}</strong> {selection.test_id} · {selection.confidence}% · {selection.reasons.join("; ")||"No supported relationship"}</li>)}</ul></details>)}</section>
    <section className="content-section"><div className="section-heading"><div><p className="eyebrow">Project and trust-domain isolated</p><h2>Content-addressed caches</h2></div><button className="danger-button" type="button" disabled={!projectID||caches.length===0} onClick={()=>void purgeCaches("")}><Trash2 aria-hidden="true"/>Purge displayed project caches</button></div>{caches.length===0?<div className="empty-state"><Database aria-hidden="true"/><div><strong>No verified cache entries</strong><p>Hits appear only after complete input identity and object integrity validation.</p></div></div>:<div className="table-scroll" tabIndex={0}><table><thead><tr><th>Kind</th><th>Trust domain</th><th>Object</th><th>Bytes</th><th>Last hit</th><th>Action</th></tr></thead><tbody>{caches.map((entry)=><tr key={entry.key}><td>{entry.kind}</td><td>{entry.trust_domain}</td><td><code>{short(entry.object_sha256)}</code></td><td>{entry.bytes.toLocaleString()}</td><td>{date(entry.last_hit_at)}</td><td><button className="tertiary-button" type="button" onClick={()=>void purgeCaches(entry.kind)}>Purge kind</button></td></tr>)}</tbody></table></div>}
      <div className="destructive-confirmation"><label>Audited reason<textarea value={reason} maxLength={1000} onChange={(event)=>setReason(event.target.value)} placeholder="Required for rebuild or cache purge"/></label><label>Current administrator password<input type="password" autoComplete="current-password" value={password} onChange={(event)=>setPassword(event.target.value)}/></label><button className="danger-button" type="button" disabled={!projectID||status?.state==="never_indexed"} onClick={()=>void rebuild()}><Trash2 aria-hidden="true"/>Clear derived index</button></div>
    </section>
  </>;
}
