import { FormEvent, useCallback, useEffect, useState } from "react";
import { BrainCircuit, Database, FileSearch, RefreshCw, Search, ShieldCheck, Trash2 } from "lucide-react";
import { api, getCSRFToken } from "./api/client";
import type { components } from "./api/schema";

type Project = components["schemas"]["Project"];
type Status = components["schemas"]["IntelligenceStatus"];
type QueryResult = components["schemas"]["IntelligenceQueryResult"];
type ContextManifest = components["schemas"]["ContextManifest"];
type ContextComparison = components["schemas"]["ContextManifestComparison"];
type Baseline = components["schemas"]["VerificationBaseline"];
type Differential = components["schemas"]["VerificationDifferential"];
type BaselineSupersession = components["schemas"]["BaselineSupersession"];
type DifferentialCorrection = components["schemas"]["DifferentialCorrection"];
type TestImpact = components["schemas"]["TestImpact"];
type TestImpactOverride = components["schemas"]["TestImpactOverride"];
type CacheEntry = components["schemas"]["CacheEntry"];
type CacheVerification = components["schemas"]["CacheVerificationReport"];
type CacheSimulation = components["schemas"]["CacheSimulation"];

function short(value?: string): string { return value ? `${value.slice(0, 12)}…` : "—"; }
function date(value?: string): string { return value ? new Date(value).toLocaleString() : "—"; }
function errorMessage(error: unknown, fallback: string): string { if (error && typeof error === "object" && "error" in error) { const nested=(error as {error?:{message?:string}}).error;if(nested?.message)return nested.message; } return fallback; }

export function IntelligencePage() {
  const [projects,setProjects]=useState<Project[]>([]);const [projectID,setProjectID]=useState("");
  const [status,setStatus]=useState<Status|null>(null);const [manifests,setManifests]=useState<ContextManifest[]>([]);const [baselines,setBaselines]=useState<Baseline[]>([]);const [differentials,setDifferentials]=useState<Differential[]>([]);const [supersessions,setSupersessions]=useState<BaselineSupersession[]>([]);const [corrections,setCorrections]=useState<DifferentialCorrection[]>([]);const [impacts,setImpacts]=useState<TestImpact[]>([]);const [impactOverrides,setImpactOverrides]=useState<TestImpactOverride[]>([]);const [caches,setCaches]=useState<CacheEntry[]>([]);
  const [query,setQuery]=useState("");const [queryResult,setQueryResult]=useState<QueryResult|null>(null);const [comparison,setComparison]=useState<ContextComparison|null>(null);const [verification,setVerification]=useState<CacheVerification|null>(null);const [simulation,setSimulation]=useState<CacheSimulation|null>(null);const [estimatedBytes,setEstimatedBytes]=useState("1048576");const [reason,setReason]=useState("");const [password,setPassword]=useState("");const [message,setMessage]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);setError("");const projectResult=await api.GET("/projects");const items=projectResult.data?.items??[];setProjects(items);const selected=projectID||items[0]?.id||"";if(!projectID&&selected)setProjectID(selected);if(!selected){setLoading(false);return}const path={projectID:selected};const [statusResult,manifestResult,baselineResult,differentialResult,supersessionResult,correctionResult,impactResult,overrideResult,cacheResult]=await Promise.all([
    api.GET("/projects/{projectID}/intelligence/status",{params:{path}}),api.GET("/projects/{projectID}/context-manifests",{params:{path}}),api.GET("/projects/{projectID}/baselines",{params:{path}}),api.GET("/projects/{projectID}/differentials",{params:{path}}),api.GET("/projects/{projectID}/baseline-supersessions",{params:{path}}),api.GET("/projects/{projectID}/differential-corrections",{params:{path}}),api.GET("/projects/{projectID}/test-impacts",{params:{path}}),api.GET("/projects/{projectID}/test-impact-overrides",{params:{path}}),api.GET("/projects/{projectID}/caches",{params:{path}}),
  ]);if(!statusResult.data)setError(errorMessage(statusResult.error,"Intelligence status could not be loaded."));setStatus(statusResult.data??null);setManifests(manifestResult.data?.items??[]);setBaselines(baselineResult.data?.items??[]);setDifferentials(differentialResult.data?.items??[]);setSupersessions(supersessionResult.data?.items??[]);setCorrections(correctionResult.data?.items??[]);setImpacts(impactResult.data?.items??[]);setImpactOverrides(overrideResult.data?.items??[]);setCaches(cacheResult.data?.items??[]);setLoading(false)},[projectID]);
  useEffect(()=>{void load()},[load]);
  const refresh=async()=>{if(!projectID)return;setError("");const result=await api.POST("/projects/{projectID}/intelligence/actions/refresh",{params:{path:{projectID},header:{"X-CSRF-Token":getCSRFToken()}}});if(!result.data){setError(errorMessage(result.error,"Trusted repository refresh failed."));return}setMessage(`Indexed ${result.data.run.files} file(s): ${result.data.run.parsed} parsed, ${result.data.run.reused} reused, ${result.data.run.failures} partial failure(s); ${result.data.source_excluded} oversized or unsupported source item(s) excluded.`);await load()};
  const search=async(event:FormEvent)=>{event.preventDefault();if(!projectID||!query.trim())return;const result=await api.POST("/projects/{projectID}/intelligence/query",{params:{path:{projectID},header:{"X-CSRF-Token":getCSRFToken()}},body:{term:query,limit:100}});if(!result.data){setError(errorMessage(result.error,"Query failed."));return}setQueryResult(result.data)};
  const compareContexts=async()=>{if(!projectID||manifests.length<2)return;setError("");const result=await api.POST("/projects/{projectID}/context-manifests/actions/compare",{params:{path:{projectID},header:{"X-CSRF-Token":getCSRFToken()}},body:{left_id:manifests[1].id,right_id:manifests[0].id}});if(!result.data){setError(errorMessage(result.error,"Context comparison failed."));return}setComparison(result.data)};
  const verifyCaches=async()=>{if(!projectID)return;setError("");const result=await api.POST("/projects/{projectID}/caches/actions/verify",{params:{path:{projectID},header:{"X-CSRF-Token":getCSRFToken()}},body:{}});if(!result.data){setError(errorMessage(result.error,"Cache verification failed."));return}setVerification(result.data)};
  const simulateCache=async(event:FormEvent)=>{event.preventDefault();if(!projectID)return;const bytes=Number(estimatedBytes);if(!Number.isSafeInteger(bytes)||bytes<0){setError("Estimated bytes must be a non-negative whole number.");return}setError("");const result=await api.POST("/projects/{projectID}/caches/actions/simulate",{params:{path:{projectID},header:{"X-CSRF-Token":getCSRFToken()}},body:{trust_domain:"trusted",kind:"source-parse",estimated_bytes:bytes}});if(!result.data){setError(errorMessage(result.error,"Cache simulation failed."));return}setSimulation(result.data)};
  const warmCaches=async()=>{if(!projectID)return;setError("");const result=await api.POST("/projects/{projectID}/caches/actions/warm",{params:{path:{projectID},header:{"X-CSRF-Token":getCSRFToken()}}});if(!result.data){setError(errorMessage(result.error,"Trusted cache warm failed."));return}setMessage(`Warmed parsed-source objects from ${result.data.run.files} exact snapshot file(s): ${result.data.run.parsed} parsed and ${result.data.run.reused} verified reuse(s).`);await load()};
  const reauthenticate=async()=>{if(!password){setError("Enter the administrator password for destructive derived-data actions.");return false}const result=await api.POST("/auth/reauthenticate",{params:{header:{"X-CSRF-Token":getCSRFToken()}},body:{password}});setPassword("");if(!result.data){setError("Reauthentication failed.");return false}return true};
  const supersedeBaseline=async(baseline:Baseline)=>{const differential=differentials.find((item)=>item.baseline_id===baseline.id);if(!projectID||!differential||!reason.trim()||!await reauthenticate())return;if(!window.confirm("Approve this candidate's stored observations as a new explicit baseline version?"))return;const result=await api.POST("/projects/{projectID}/baselines/{baselineID}/actions/supersede",{params:{path:{projectID,baselineID:baseline.id},header:{"X-CSRF-Token":getCSRFToken()}},body:{differential_id:differential.id,reason}});if(!result.data){setError(errorMessage(result.error,"Baseline update failed."));return}setMessage(`Created replacement baseline ${result.data.replacement.id}; original evidence remains immutable.`);await load()};
  const correctDifferential=async(differential:Differential,item:Differential["items"][number])=>{if(!projectID||!reason.trim()||!await reauthenticate())return;const result=await api.POST("/projects/{projectID}/differentials/{differentialID}/actions/correct",{params:{path:{projectID,differentialID:differential.id},header:{"X-CSRF-Token":getCSRFToken()}},body:{observation_kind:item.kind,observation_key:item.key,after_classification:"indeterminate",reason}});if(!result.data){setError(errorMessage(result.error,"Classification correction failed."));return}setMessage(`Recorded attributed correction from ${result.data.before_classification.replaceAll("_"," ")} to indeterminate.`);await load()};
  const overrideImpact=async(impact:TestImpact,testID:string,selected:boolean)=>{if(!projectID||!reason.trim()||!await reauthenticate())return;const result=await api.POST("/projects/{projectID}/test-impacts/{impactID}/actions/override",{params:{path:{projectID,impactID:impact.id},header:{"X-CSRF-Token":getCSRFToken()}},body:{test_id:testID,selected,reason}});if(!result.data){setError(errorMessage(result.error,"Test-impact override failed."));return}setMessage(`Recorded targeted-test override; the full-suite requirement remains ${impact.full_suite_required?"mandatory":"unchanged"}.`);await load()};
  const rebuild=async()=>{if(!projectID||!reason.trim()||!await reauthenticate())return;if(!window.confirm("Clear this project's derived index? Durable source and job evidence are not deleted."))return;const result=await api.POST("/projects/{projectID}/intelligence/actions/rebuild",{params:{path:{projectID},header:{"X-CSRF-Token":getCSRFToken()}},body:{reason}});if(!result.data){setError(errorMessage(result.error,"Rebuild clear failed."));return}setMessage("Derived index cleared. Run Refresh index to build it from the exact synchronized Git revision.");await load()};
  const purgeCaches=async(kind:string)=>{if(!projectID||!reason.trim()||!await reauthenticate())return;const matching=caches.filter((entry)=>!kind||entry.kind===kind).length;if(!window.confirm(`Purge ${matching} displayed ${kind||"all"} cache entr${matching===1?"y":"ies"} for ${projectID}?`))return;const result=await api.POST("/projects/{projectID}/caches/actions/purge",{params:{path:{projectID},header:{"X-CSRF-Token":getCSRFToken()}},body:{kind,reason}});if(!result.data){setError(errorMessage(result.error,"Cache purge failed."));return}setMessage(`Purged ${result.data.purged} exact cache entr${result.data.purged===1?"y":"ies"}.`);await load()};
  return <>
    <p className="page-intro">Inspect project-separated blob-hash analysis, deterministic context selection, clean-environment differentials, explainable test impact, and verified cache provenance.</p>
    <section className="configuration-toolbar" aria-label="Code intelligence project controls"><label>Registered project<select value={projectID} onChange={(event)=>setProjectID(event.target.value)}><option value="">Select a project</option>{projects.map((project)=><option key={project.id} value={project.id}>{project.id} · {project.repository}</option>)}</select></label><button type="button" disabled={!projectID||loading||status?.indexing_enabled===false} onClick={()=>void refresh()}><RefreshCw aria-hidden="true"/>Refresh index</button><button className="secondary-button" type="button" disabled={!projectID||loading} onClick={()=>void load()}><RefreshCw aria-hidden="true"/>Reload evidence</button></section>
    {error&&<p className="error" role="alert">{error}</p>}{message&&<p className="inline-message" role="status">{message}</p>}
    <div className="configuration-summary"><div><span>Index state</span><strong>{status?.indexing_enabled===false?"paused":status?.state??"—"}</strong></div><div><span>Files</span><strong>{status?.files??0}</strong></div><div><span>Partial failures</span><strong>{status?.failures??0}</strong></div><div><span>Retention</span><strong>{status?.retention_days??30} days</strong></div><div><span>Cache quota</span><strong>{(status?.cache_quota_bytes??0).toLocaleString()}</strong></div></div>
    <section className="content-section"><div className="section-heading"><div><p className="eyebrow">Freshness and coverage</p><h2>Project index</h2></div><BrainCircuit aria-hidden="true"/></div>{!status||status.state==="never_indexed"?<div className="empty-state"><FileSearch aria-hidden="true"/><div><strong>No index run yet</strong><p>Refresh reads a bounded exact snapshot from the credential-isolated Git bridge; source bytes are never accepted from this browser.</p></div></div>:<div className="detail-grid"><article><h3>Revision</h3><code>{status.latest_revision}</code><p>{date(status.fresh_at)}</p></article><article><h3>Languages and tools</h3><p>{status.languages.join(", ")||"None classified"}</p><small>{[...status.parser_ids,...status.tool_ids].join(", ")}</small></article><article><h3>Run identity</h3><code>{status.latest_run_id}</code><p>Blob results are reused only within this project/repository/parser identity.</p></article></div>}
      <form className="intelligence-query" onSubmit={(event)=>void search(event)}><label>Graph query<input type="search" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Symbol, import, or repository path"/></label><button type="submit" disabled={!projectID||!query.trim()}><Search aria-hidden="true"/>Query evidence</button></form>
      {queryResult&&<div className="query-results"><p>{queryResult.partial?"Partial index: failures remain visible.":"Complete indexed evidence."} {queryResult.symbols.length} symbol(s), {queryResult.relations.length} relation(s).</p><div className="table-scroll" tabIndex={0}><table><thead><tr><th>Symbol</th><th>Kind</th><th>Location</th><th>Confidence</th></tr></thead><tbody>{queryResult.symbols.map((symbol)=><tr key={symbol.id}><td>{symbol.name}</td><td>{symbol.kind}</td><td><code>{symbol.path}:{symbol.start_line}</code></td><td>{symbol.confidence}%</td></tr>)}</tbody></table></div></div>}
    </section>
    <section className="content-section"><div className="section-heading"><div><p className="eyebrow">Bounded deterministic packets</p><h2>Context manifests</h2></div><button className="secondary-button" type="button" disabled={!projectID||manifests.length<2} onClick={()=>void compareContexts()}><ShieldCheck aria-hidden="true"/>Compare newest two</button></div>{comparison&&<div className="inline-message" role="status"><strong>Manifest delta</strong><p>{comparison.added.length} added, {comparison.removed.length} removed, {comparison.changed.length} changed · input token delta {comparison.input_token_delta>0?"+":""}{comparison.input_token_delta} · reserve delta {comparison.output_reserve_delta>0?"+":""}{comparison.output_reserve_delta}{comparison.truncation_changed?" · truncation state changed":""}.</p></div>}{manifests.length===0?<div className="empty-state"><Database aria-hidden="true"/><div><strong>No compiled contexts yet</strong><p>Workflow stages record selection reasons, hashes, trust, cost, exclusions, staleness, and reserved output budget—never hidden reasoning.</p></div></div>:<div className="evidence-stack">{manifests.map((manifest)=><details key={manifest.id}><summary><code>{manifest.id}</code> · {manifest.stage} · {manifest.used_tokens}/{manifest.budget_tokens-manifest.reserved_output_tokens} input tokens</summary><p>{manifest.truncated?"Budget truncation occurred.":"All eligible content fit."} Created {date(manifest.created_at)}.</p><ul>{manifest.selections.map((selection)=><li key={selection.id}><strong>{selection.included?"Included":"Excluded"}</strong> {selection.source} / {selection.id}: {selection.reason} · {selection.estimated_tokens} tokens · {selection.trust}{selection.exclusion?` · ${selection.exclusion}`:""}</li>)}</ul></details>)}</div>}</section>
    <section className="content-section"><div className="section-heading"><div><p className="eyebrow">Fresh clean-environment evidence</p><h2>Baselines and differentials</h2></div><span>{baselines.length} baseline(s) · {supersessions.length} approved update(s)</span></div>{baselines.length===0?<div className="empty-state"><ShieldCheck aria-hidden="true"/><div><strong>No workflow baseline captured</strong><p>Agents cannot create or approve baseline state. A policy-bound clean verification phase records the first immutable baseline.</p></div></div>:<div className="evidence-stack">{baselines.map((baseline)=><article key={baseline.id}><strong>{baseline.reason}</strong><p><code>{short(baseline.revision)}</code> · {baseline.toolchain_id} · {baseline.observations.length} observation(s) · {date(baseline.created_at)}</p>{differentials.some((item)=>item.baseline_id===baseline.id)&&<button className="tertiary-button" type="button" onClick={()=>void supersedeBaseline(baseline)}>Approve candidate as new baseline</button>}</article>)}</div>}{supersessions.map((item)=><p className="inline-message" key={item.id}><strong>Approved baseline update</strong> {item.baseline_id} → {item.replacement.id} by {item.actor_id}: {item.reason}</p>)}{differentials.map((differential)=><details key={differential.id}><summary>{differential.purpose} · {short(differential.candidate_sha)} against {differential.baseline_id}</summary><ul>{differential.items.map((item)=><li key={`${item.kind}-${item.key}`}><strong>{item.classification.replaceAll("_"," ")}</strong> {item.kind}/{item.key}: {item.explanation} {item.classification!=="indeterminate"&&<button className="tertiary-button" type="button" onClick={()=>void correctDifferential(differential,item)}>Correct to indeterminate</button>}</li>)}</ul></details>)}{corrections.map((item)=><p key={item.id}><strong>Correction history:</strong> {item.observation_kind}/{item.observation_key} · {item.before_classification.replaceAll("_"," ")} → {item.after_classification.replaceAll("_"," ")} by {item.actor_id}: {item.reason}</p>)}</section>
    <section className="content-section"><div className="section-heading"><div><p className="eyebrow">Fast inner loop, full final gate</p><h2>Test impact</h2></div><span>{impacts.length} record(s) · {impactOverrides.length} override(s)</span></div>{impacts.length===0?<div className="empty-state"><FileSearch aria-hidden="true"/><div><strong>No changed-symbol impact yet</strong><p>Selections will cite coverage/index relationships and omissions. Targeted tests never replace the policy-required fresh full suite.</p></div></div>:impacts.map((impact)=><details key={impact.id}><summary>{short(impact.revision)} · {impact.selections.filter((item)=>item.selected).length} targeted · full suite {impact.full_suite_required?"required":"policy dependent"}</summary><p>{impact.policy_explanation}</p><ul>{impact.selections.map((selection)=><li key={selection.test_id}><strong>{selection.selected?"Selected":"Omitted"}</strong> {selection.test_id} · {selection.confidence}% · {selection.reasons.join("; ")||"No supported relationship"} <button className="tertiary-button" type="button" onClick={()=>void overrideImpact(impact,selection.test_id,!selection.selected)}>{selection.selected?"Override omission":"Override inclusion"}</button></li>)}</ul></details>)}{impactOverrides.map((item)=><p key={item.id}><strong>Override history:</strong> {item.test_id} · {item.selected?"included":"omitted"} by {item.actor_id}: {item.reason}{item.expires_at?` · expires ${date(item.expires_at)}`:""}</p>)}</section>
    <section className="content-section"><div className="section-heading"><div><p className="eyebrow">Project and trust-domain isolated</p><h2>Content-addressed caches</h2></div><button className="danger-button" type="button" disabled={!projectID||caches.length===0} onClick={()=>void purgeCaches("")}><Trash2 aria-hidden="true"/>Purge displayed project caches</button></div><div className="configuration-toolbar" aria-label="Cache integrity controls"><button className="secondary-button" type="button" disabled={!projectID||caches.length===0} onClick={()=>void verifyCaches()}><ShieldCheck aria-hidden="true"/>Verify cache objects</button><button className="secondary-button" type="button" disabled={!projectID||status?.indexing_enabled===false} onClick={()=>void warmCaches()}><RefreshCw aria-hidden="true"/>Warm from trusted snapshot</button><form className="intelligence-query" onSubmit={(event)=>void simulateCache(event)}><label>Estimated parsed object bytes<input type="number" min="0" step="1" value={estimatedBytes} onChange={(event)=>setEstimatedBytes(event.target.value)}/></label><button type="submit" disabled={!projectID||estimatedBytes===""}>Simulate quota</button></form></div>{verification&&<div className="inline-message" role="status"><strong>Integrity recomputation complete</strong><p>{verification.verified} verified, {verification.invalid} invalid, {verification.unavailable} unavailable.</p></div>}{simulation&&<div className={simulation.would_fit?"inline-message":"error"} role="status"><strong>{simulation.would_fit?"Estimate fits":"Estimate exceeds quota"}</strong><p>{simulation.current_bytes.toLocaleString()} current + {simulation.estimated_bytes.toLocaleString()} estimated of {simulation.quota_bytes.toLocaleString()} bytes. {simulation.explanation}</p></div>}{caches.length===0?<div className="empty-state"><Database aria-hidden="true"/><div><strong>No verified cache entries</strong><p>Hits appear only after complete input identity and object integrity validation.</p></div></div>:<div className="table-scroll" tabIndex={0}><table><thead><tr><th>Kind</th><th>Trust domain</th><th>Result</th><th>Object</th><th>Bytes / quota</th><th>Expiry</th><th>Action</th></tr></thead><tbody>{caches.map((entry)=><tr key={entry.key}><td>{entry.kind}</td><td>{entry.trust_domain}</td><td><strong>{entry.last_result}</strong><small>{entry.result_reason}</small></td><td><code>{short(entry.object_sha256)}</code></td><td>{entry.bytes.toLocaleString()} / {entry.quota_bytes.toLocaleString()}</td><td>{date(entry.expires_at)}</td><td><button className="tertiary-button" type="button" onClick={()=>void purgeCaches(entry.kind)}>Purge kind</button></td></tr>)}</tbody></table></div>}
      <div className="destructive-confirmation"><label>Audited reason<textarea value={reason} maxLength={1000} onChange={(event)=>setReason(event.target.value)} placeholder="Required for rebuild, purge, correction, baseline update, or targeted-test override"/></label><label>Current administrator password<input type="password" autoComplete="current-password" value={password} onChange={(event)=>setPassword(event.target.value)}/></label><button className="danger-button" type="button" disabled={!projectID||status?.state==="never_indexed"} onClick={()=>void rebuild()}><Trash2 aria-hidden="true"/>Clear derived index</button></div>
    </section>
  </>;
}
